version: "3.2"

services:
  memcached1:
    container_name: test_memcached_1
    image: memcached:1.6.17-alpine
    ports:
      - "11211:11211"

  memcached2:
    container_name: test_memcached_2
    image: memcached:1.6.17-alpine
    ports:
      - "11212:11211"
